### PR TITLE
Use HookContainer to register hooks

### LINKED ISSUE #235: Several deprecation notices on hooks
**DynamicPageList3 version**: 3.5.2 (1ac24116bf0e6ebc042409a8160a6cfaaea66838)
**MediaWiki version**: 1.40.0
**PHP version**: 8.1.17

**List of steps to reproduce** (step by step, including full links if applicable):
* Turn error_reporting on
* Go to a page that uses DPL3
* See deprecation notices

**What happens?**:
Several deprecation notices show on top of the page:
```
Deprecated: Accessing $wgHooks directly is deprecated, use HookContainer::isRegistered() instead. [Called from MediaWiki\Extension\DynamicPageList3\Parse::triggerEndResets in /www/wwwroot/podcast/extensions/DynamicPageList3/includes/Parse.php at line 962] in
/www/wwwroot/podcast/includes/debug/MWDebug.php on line 382


Deprecated: Accessing $wgHooks directly is deprecated, use HookContainer::getHandlers() or HookContainer::register() instead. [Called from MediaWiki\Extension\DynamicPageList3\Parse::triggerEndResets in /www/wwwroot/podcast/extensions/DynamicPageList3/includes/Parse.php at line 962] in
/www/wwwroot/podcast/includes/debug/MWDebug.php on line 382

Deprecated: ParserOutput::mCategories public read access deprecated [Called from MediaWiki\Extension\DynamicPageList3\Hooks::endReset in /www/wwwroot/podcast/extensions/DynamicPageList3/includes/Hooks.php at line 559] in
/www/wwwroot/podcast/includes/debug/MWDebug.php on line 382
```

**What should have happened instead?**:
No deprecation notices

### PR DESCRIPTION
**Pull request by Universal-Omega**
Manipulating $wgHooks is deprecated

Fixes #235

### CODE REVIEW

**Comment by tyrann0us** [comment]
Hi @Universal-Omega, thanks for the PR! Do you have any plans to merge this or are there still any known issues?
The deprecating errors are "spamming" my logs, so a fix would be greatly appreciated.
Thank you very much!

**Comment by Universal-Omega** [comment]
> Hi @Universal-Omega, thanks for the PR! Do you have any plans to merge this or are there still any known issues? The deprecating errors are "spamming" my logs, so a fix would be greatly appreciated. Thank you very much!

@tyrann0us 

It just that this is untested if your able to test I can merge otherwise it will take a little while longer for me to be able to test...

**Comment by tyrann0us** [comment]
@Universal-Omega, thanks for getting back to me. I applied the fix from this PR to the extension sometime after my above comment, and while I only use DPL for one very basic query, the deprecation notices stopped showing up in the logs. Therefore, this should be good to go.

BTW, the referenced issue (#235) also mentions `Deprecated: ParserOutput::mCategories public read access deprecated`, which I also see a lot in my logs. It was fixed in #215 already. Do you have an ETA for a new release of DynamicPageList3 that will include both fixes?
Thank you!

**Comment by Universal-Omega** [comment]
I will probably make a new release either this week or next week.

**Pull request merged**
